
name: Run Jest Tests

# push or PR
on: [push, pull_request]

permissions:
    contents: read
    checks: write

jobs:
  build:
    # This GitHub workflow runs on the latest version of Ubuntu (same as azure)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      # configures a Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '21'

    # Node Modules caching
    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/backend/package-lock.json') }}-v1
        restore-keys: |
          ${{ runner.os }}-node-

    # Install the node project dependencies
    - name: Install Dependencies
      run:  |
        cd ./backend
        npm install

    # Now that the environment is set up, run the actual tests using npm run test command
    - name: Run Jest Tests
      run: |
        cd ./backend/BackendTest
        npm run test

    # publish with  "action-junit-report" 
    - name: Publish Test Results
      if: always()
      uses: mikepenz/action-junit-report@v3
      with:
        check_name: 'Test Report'
        report_paths: 'backend/testResult/junit.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}
